[[rules]]
  id = 'c42a367392fc3aadefbf9caa4de4582a790b8746ed72e6e97fca6f962502597a'
  description = 'ArgoCD JWT'
  # Based on shifted b64 encoded portions of '"iss":"argocd"'
  regex = '''([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_]+(?:ImlzcyI6ImFyZ29jZC|Jpc3MiOiJhcmdvY2Qi|iaXNzIjoiYXJnb2NkI)[a-zA-Z0-9-_]+\.[a-zA-Z0-9-_]+)'''
  tags = ['alert:repo-owner', 'type:secret']
  secretGroup = 1
  # keywords = [
  #   'ImlzcyI6ImFyZ29jZC',
  #   'Jpc3MiOiJhcmdvY2Qi',
  #   'iaXNzIjoiYXJnb2NkI',
  # ]
