# Genearal Potential Leak Patterns

# TODO: this is just stubbed out so that the files exist
# pattenrs still need to be moved over

# Very WIP just here to unblock some testing
[[rules]]
  id = "private-key"
  description = "Private Key"
  regex = '''(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY( BLOCK)?-----[\s\S-]*?-----END[ A-Z0-9_-]{0,100}PRIVATE KEY( BLOCK)?-----'''
  tags = ["group:leaktk-testing", "alert:repo-owner", "type:secret"]
  keywords = ["-----begin"]

  [rules.allowlist]
    paths = [
      # Ignore common test certs
      '''test(s)?\/[\w\-]+.pem$''',
      # Ignore common example keys
      '''example.*(key|pem)''',
      # Ignore common openssl tests
      '''test\/(recipes|smime-certs|certs)\/.+\.(txt|der|key|pem)''',
    ]

    regexes = [
      # Anything less than 15 characters
      '''PRIVATE KEY( BLOCK)?-----.{0,15}-----END''',
      # An inline key that has spaces in it
      '''PRIVATE KEY( BLOCK)?-----.+\s.+-----END''',
    ]

[[rules]]
  id = "aws-iam-unique-id"
  description = "AWS IAM Unique Identifier"
  regex = '''[^A-Z0-9]((A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16})'''
  secretGroup = 1
  entropy = 3.2
  tags = ["group:leaktk-testing", "alert:repo-owner", "type:secret"]
  keywords = ["a3t", "akia", "agpa", "aida", "aroa", "aipa", "anpa", "anva", "asia"]

  [rules.allowlist]
    regexes = [
      # Ingore example keys
      '''EXAMPLE''',
    ]

[[rules]]
  id = "aws-secret-key"
  description = "AWS Secret Key"
  regex = '''(?i)aws([^:=(,\/\s]{0,20})?(\s+)?[:=(](\s+)?(?-i)['\"]?([A-Za-z0-9\/+]{40})['\"]?'''
  secretGroup = 4
  entropy = 4
  tags = ["group:leaktk-testing", "alert:repo-owner", "type:secret"]
  keywords = ["aws"]

  [rules.allowlist]
    regexes = [
      # Ignore common placeholders
      '''(?i)aws([^:=(,\/\s]{0,20})?(\s+)?[:=(](\s+)?['\"]?.*(example|abcdef|get|name|serv|spec|profile|role|resource|test|curl|cont|conf|cert).*['\"]?''',
      # Ignore EXAMPLE base64 encoded
      '''(?i)aws([^:=(,\/\s]{0,20})?(\s+)?[:=(](\s+)?['\"]?.*(?-i)(RVhBTVBMR|VYQU1QTEU|FWEFNUExF).*['\"]?''',
    ]
