#! /usr/bin/env bash
set -euo pipefail

declare -A ltk_dgst_map=(
  ['leaktk-0.2.0-linux-x86_64.tar.xz']='9982ee62e625899098873c6c5bf2f309f56a76772f9c4b95b95e2ac82adcf8d2'
  ['leaktk-0.2.0-linux-arm64.tar.xz']='0ff1d7c001d15890d62cdbdb6bcb7368f1266d00141b2a6a3b1a80d5f1381121'
  ['leaktk-0.2.0-darwin-x86_64.tar.xz']='c139bc130d21e8c49dff002ad0b30ceb5d8a01944f0b4feff60f8e5cb641cda0'
  ['leaktk-0.2.0-darwin-arm6.tar.xz']='fe5ecdc1377aba76bedc36a5a72d2aa171636dfd40c188b7c879417ffc85c5fa'
)

ltk_version="0.2.0"
ltk_artifact="leaktk-${ltk_version}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed -e 's/^aarch/arm/').tar.xz"
ltk_dl_url="https://github.com/leaktk/leaktk/releases/download/v${ltk_version}/${ltk_artifact}"
ltk_bin_cache_dir="${XDG_CACHE_HOME:-"${HOME}/.cache"}/leaktk/patterns/testdata/bin"
ltk_bin="${ltk_bin_cache_dir}/leaktk-${ltk_dgst_map[${ltk_artifact}]}"

if [[ ! -x "${ltk_bin}" ]]
then
  ltk_bin_tar_xz="${ltk_bin}.tar.xz"
  mkdir -p "${ltk_bin_cache_dir}"
  curl \
    --fail \
    --silent \
    --location \
    --url "${ltk_dl_url}" \
    --output "${ltk_bin_tar_xz}"

  if echo "${ltk_dgst_map[${ltk_artifact}]}  ${ltk_bin_tar_xz}" | sha256sum -c - &> /dev/null
  then
    tar -C "${ltk_bin_cache_dir}" -xJf "${ltk_bin_tar_xz}" leaktk
    rm "${ltk_bin_tar_xz}"
    mv "${ltk_bin_cache_dir}/leaktk" "${ltk_bin}"
  else
    echo "inalid checksum: $(sha256sum "${ltk_bin_tar_xz}")"
    rm "${ltk_bin_tar_xz}"
    exit 1
  fi
fi

exec "${ltk_bin}" $@
