#! /usr/bin/env python3

import yaml
import sys

from collections import defaultdict

def str_presenter(dumper, data):
    """
    Display multi-line values using |-
    """
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")

    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


yaml.add_representer(str, str_presenter)


with open(sys.argv[1], encoding="UTF-8") as results_file:
    results = yaml.load(results_file, yaml.SafeLoader)


groups = defaultdict(list)
for result in results:
    group_key = result[list(result)[0]]
    groups[group_key].append(result)

with open(sys.argv[1], "w", encoding="UTF-8") as results_file:
    results_file.write("# Use scripts/sort-and-group-in-place to sort this file\n")
    for group in sorted(groups):
        results = groups[group]
        keys = list(sorted(results[0].keys()))
        results = list(sorted(results, key=lambda r: tuple(map(r.get, keys))))
        results_file.write(f"\n#\n# {group}\n#\n")

        for result in results:
            results_file.write("\n")
            yaml.dump([result], results_file, default_flow_style=False, sort_keys=False)
