#! /bin/bash
set -euo pipefail
export PATH="$(pwd)/scripts:${PATH}"

echo 'Testng the-valid-tag-format...'
echo
if grep -RP 'tags(\s+)?=(\s+)?\[' 'patterns/gitleaks/' | sed 's/.*:.*tags.*=.*\[//g' | sed 's/\].*//g' | grep -vP  '^[0-9a-z\s:\",-]+$$'
then
  echo
  echo '^^^ A line was found with an invalid character'
  echo
  exit 1
else
  echo 'OK'
fi

echo 'Checking for type tags...'
echo
if grep -RP 'tags(\s+)?=(\s+)?\[' 'patterns/gitleaks/' | grep -v '"type:secret"'
then
  echo
  echo '^^^ Missing "type:" tags detected'
  echo
  exit 1
else
  echo 'OK'
fi


for version in $(./scripts/versions)
do
  make "target/patterns/gitleaks/${version}"
  (cd "tests/gitleaks/${version}" && python3 -m unittest test_gitleaks.py)
done
