[[allowlists]]
  description = "Global Allowlist"
  regexTarget = "line"
  regexes = [
      # Use 'notsecret' as the standard allow tag anywhere in the result
      # context.
      #
      # Example:
      #
      #   some_secret="-VPUsquZ_RA" # notsecret
      #
      # Also currently ignores formats like:
      #
      #   - NOTSECRET
      #   - NotSecret
      #   - not_secret
      #   - not-secret
      #   - not secret
      #
      '''(?i)\bnot[\t\x20\-\_]*secret\b'''
  ]

  paths = [
      # Ignore common binary file types
      '''(?i)\.(?:[sk]?o|a|bin|bmp|class|css|dat|deb|dll|docx?|ear|exe|gif|img|iso|jar|jpe?g|lib|mp4|pcap|pdf|png|py[co]|pyc|qcow2|raw|rpm|socket|svg|war|xlsx?)$''',
      # Ignore most quickstarts
      '''quickstart''',
      # Ignore vendored code
      '''vendor|(?:^|\/)(?:gems|node_modules|GoDeps)\/''',
      # Ignore go.mod and go.sum files
      '''(?:^|\/)go\.(?:mod|sum)$''',
      # Ignore betterleaks gitleaks related stuff
      '''(?:^|\/).?(?:better|git)leaks''',
      # Ignore checked-in python packages
      '''(?:^|\/)lib\/python[^/]+\/site-packages''',
      # Handle a lot of the github/docs cases
      '''(?:^|\/)lib\/rest\/static\/.+\/(?:.*?github.+\.json|ghes.+\.json)''',
      # Ignore aws secrets
      '''(?:^|\/)\.?secrets.baseline$''',
      # Ignore a github spec file
      '''(?:^|\/)specs\/github\.(?:ya?ml|json)$''',
      # Ignore yarn release files
      '''(?:^|\/).yarn\/releases\/''',
      # Ignore .git file/folders
      '''(?:^|\/)\.git$''',
  ]
